### ISSUE TITLE
seems that SignalChangedMessage.java is missing

### ISSUE THREAD

**Issue by kaback** [zherebjatjew/morse#1]
Hi,

i would like build your app, but build fails because $PROJECT_DIR$/src/com/android/dj/morse/flow/SignalChangedMessage.java is missing.

Could you please add this file to your repository?

Thnaks!

**Comment by zherebjatjew** [comment]
Hi,

Unfortunately I can not help. The project has been frozen long time ago,
and I do not plan to work on it in observable future.
29 окт. 2015 г. 17:59 пользователь "Karsten von Hornbostel" <
notifications@github.com> написал:

**Comment by kaback** [comment]
Hi,

and there is no way to provide the missing file to me?

Regards,
Karsten

**Comment by zherebjatjew** [comment]
As the project is incomplete, it might be that the file has never existed.
The repo contains the most recent version, so if there is no file in any of
the branches, it just have not been created.
29 окт. 2015 г. 18:54 пользователь "Karsten von Hornbostel" <
notifications@github.com> написал:

**Comment by kaback** [comment]
Ok, thanks.
